language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
script:
 - dotnet restore "src\CodeProxy\CodeProxy.csproj"
 - dotnet build -f netstandard1.6 "src\CodeProxy\CodeProxy.csproj"
 - dotnet restore "tests\CodeProxy.Tests\CodeProxy.Tests.csproj"
 - dotnet test "tests\CodeProxy.Tests\CodeProxy.Tests.csproj"