language: csharp
solution: CodeProxy.sln
install:
  - mono .nuget/NuGet.exe restore CodeProxy.sln
# - nuget restore XProxy.sln
# - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory build
script:
  - xbuild /p:Configuration=Release CodeProxy.sln
# - mono ./build/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./tests/XProxy.Tests/bin/Release/XProxy.Tests.dll  --where "cat != BuildOmit"